# values.yaml
credentials:
  useSecret: true
  secretContents:
    cloud: |
      [default]
      aws_access_key_id = ${access_key}
      aws_secret_access_key = ${secret_access_key}
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.9.0
    volumeMounts:
      - mountPath: /target
        name: plugins
configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: ${bucket_name}
      config:
        region: ${region}
        s3ForcePathStyle: "true"
  volumeSnapshotLocation:
    - name: default
      provider: aws
