apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-asmaa
spec:
  acme:
    email: asmaa.khaider@outlook.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-asmaa
    solvers:
      - http01:
          ingress:
            class: nginx
